### ISSUE TITLE
[IMPR][gpc-test-data] Allow loading files not containing any test data

### ISSUE THREAD

**Issue by taughty** [gherking/gpc-test-data#9]
## Summary
Currently, a validation error happens if the referenced input file does not contain any test data, e.g. the JSON file contains an empty array. I want to be able to turn off this validation by a precompiler configuration.

## Use cases
When using test data files being generated dinamically, there may be cases when empty test data files are considered to be expected and valid. As a result, the outline scenario may not be executed due to an empty Examples section.

**Comment by szikszail** [comment]
@taughty feel free to go ahead and implement your suggestions :)

**Comment by szikszail** [comment]
@taughty `gpc-test-data@1.2.0` is released. Thank you for your contribution!
